//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knowledgeable
{
    using System;
    using System.Collections.Generic;
    
    public partial class Colour
    {
        public System.Guid ColourID { get; set; }
        public string ColourName { get; set; }
        public byte[] Hex { get; set; }
    }
}
